# Generated by Django 4.1.5 on 2023-01-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='gender',
            new_name='speech_gender',
        ),
    ]
