# Generated by Django 4.1.5 on 2023-01-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_translationinput_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationoutput',
            name='input',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.translationinput'),
            preserve_default=False,
        ),
    ]
