# Generated by Django 4.1.5 on 2023-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_translationoutput_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='speech_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
