# Generated by Django 4.1.5 on 2023-01-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userconfig_speech_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationoutput',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.translationinput'),
        ),
    ]
