# Generated by Django 4.1.5 on 2023-01-14 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_translationoutput_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationoutput',
            name='pos',
            field=models.JSONField(default={}, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='alternative_translations_count',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='repeat_speech_count',
            field=models.CharField(choices=[('one', 'one'), ('three', 'three'), ('five', 'five'), ('nine', 'nine')], default='one', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='speech_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='speech_speed',
            field=models.CharField(choices=[('very_slow', 'very_slow'), ('slow', 'slow'), ('normal', 'normal'), ('fast', 'fast')], default='normal', max_length=255),
        ),
    ]
